/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedTeamStatisticsRouteImport } from './routes/_authenticated/team-statistics'
import { Route as AuthenticatedSystemStatusRouteImport } from './routes/_authenticated/system-status'
import { Route as AuthenticatedStandingsRouteImport } from './routes/_authenticated/standings'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSeasonsRouteImport } from './routes/_authenticated/seasons'
import { Route as AuthenticatedPredictionsRouteImport } from './routes/_authenticated/predictions'
import { Route as AuthenticatedPowerRankingsRouteImport } from './routes/_authenticated/power-rankings'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedLearningRouteImport } from './routes/_authenticated/learning'
import { Route as AuthenticatedIntelligenceRouteImport } from './routes/_authenticated/intelligence'
import { Route as AuthenticatedFixturesRouteImport } from './routes/_authenticated/fixtures'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompetitionsRouteImport } from './routes/_authenticated/competitions'
import { Route as AuthenticatedBacktestingRouteImport } from './routes/_authenticated/backtesting'
import { Route as AuthenticatedTeamsIdRouteImport } from './routes/_authenticated/teams.$id'
import { Route as AuthenticatedFixturesIdRouteImport } from './routes/_authenticated/fixtures.$id'
import { Route as AuthenticatedCompetitionsIdRouteImport } from './routes/_authenticated/competitions.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamStatisticsRoute =
  AuthenticatedTeamStatisticsRouteImport.update({
    id: '/team-statistics',
    path: '/team-statistics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemStatusRoute =
  AuthenticatedSystemStatusRouteImport.update({
    id: '/system-status',
    path: '/system-status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStandingsRoute = AuthenticatedStandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeasonsRoute = AuthenticatedSeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPredictionsRoute =
  AuthenticatedPredictionsRouteImport.update({
    id: '/predictions',
    path: '/predictions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPowerRankingsRoute =
  AuthenticatedPowerRankingsRouteImport.update({
    id: '/power-rankings',
    path: '/power-rankings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearningRoute = AuthenticatedLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntelligenceRoute =
  AuthenticatedIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFixturesRoute = AuthenticatedFixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompetitionsRoute =
  AuthenticatedCompetitionsRouteImport.update({
    id: '/competitions',
    path: '/competitions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBacktestingRoute =
  AuthenticatedBacktestingRouteImport.update({
    id: '/backtesting',
    path: '/backtesting',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamsIdRoute = AuthenticatedTeamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTeamsRoute,
} as any)
const AuthenticatedFixturesIdRoute = AuthenticatedFixturesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedFixturesRoute,
} as any)
const AuthenticatedCompetitionsIdRoute =
  AuthenticatedCompetitionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCompetitionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/backtesting': typeof AuthenticatedBacktestingRoute
  '/competitions': typeof AuthenticatedCompetitionsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fixtures': typeof AuthenticatedFixturesRouteWithChildren
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/power-rankings': typeof AuthenticatedPowerRankingsRoute
  '/predictions': typeof AuthenticatedPredictionsRoute
  '/seasons': typeof AuthenticatedSeasonsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/standings': typeof AuthenticatedStandingsRoute
  '/system-status': typeof AuthenticatedSystemStatusRoute
  '/team-statistics': typeof AuthenticatedTeamStatisticsRoute
  '/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/competitions/$id': typeof AuthenticatedCompetitionsIdRoute
  '/fixtures/$id': typeof AuthenticatedFixturesIdRoute
  '/teams/$id': typeof AuthenticatedTeamsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/backtesting': typeof AuthenticatedBacktestingRoute
  '/competitions': typeof AuthenticatedCompetitionsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fixtures': typeof AuthenticatedFixturesRouteWithChildren
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/power-rankings': typeof AuthenticatedPowerRankingsRoute
  '/predictions': typeof AuthenticatedPredictionsRoute
  '/seasons': typeof AuthenticatedSeasonsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/standings': typeof AuthenticatedStandingsRoute
  '/system-status': typeof AuthenticatedSystemStatusRoute
  '/team-statistics': typeof AuthenticatedTeamStatisticsRoute
  '/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/competitions/$id': typeof AuthenticatedCompetitionsIdRoute
  '/fixtures/$id': typeof AuthenticatedFixturesIdRoute
  '/teams/$id': typeof AuthenticatedTeamsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/backtesting': typeof AuthenticatedBacktestingRoute
  '/_authenticated/competitions': typeof AuthenticatedCompetitionsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fixtures': typeof AuthenticatedFixturesRouteWithChildren
  '/_authenticated/intelligence': typeof AuthenticatedIntelligenceRoute
  '/_authenticated/learning': typeof AuthenticatedLearningRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/power-rankings': typeof AuthenticatedPowerRankingsRoute
  '/_authenticated/predictions': typeof AuthenticatedPredictionsRoute
  '/_authenticated/seasons': typeof AuthenticatedSeasonsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/standings': typeof AuthenticatedStandingsRoute
  '/_authenticated/system-status': typeof AuthenticatedSystemStatusRoute
  '/_authenticated/team-statistics': typeof AuthenticatedTeamStatisticsRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/_authenticated/competitions/$id': typeof AuthenticatedCompetitionsIdRoute
  '/_authenticated/fixtures/$id': typeof AuthenticatedFixturesIdRoute
  '/_authenticated/teams/$id': typeof AuthenticatedTeamsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/backtesting'
    | '/competitions'
    | '/dashboard'
    | '/fixtures'
    | '/intelligence'
    | '/learning'
    | '/performance'
    | '/power-rankings'
    | '/predictions'
    | '/seasons'
    | '/settings'
    | '/standings'
    | '/system-status'
    | '/team-statistics'
    | '/teams'
    | '/competitions/$id'
    | '/fixtures/$id'
    | '/teams/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/backtesting'
    | '/competitions'
    | '/dashboard'
    | '/fixtures'
    | '/intelligence'
    | '/learning'
    | '/performance'
    | '/power-rankings'
    | '/predictions'
    | '/seasons'
    | '/settings'
    | '/standings'
    | '/system-status'
    | '/team-statistics'
    | '/teams'
    | '/competitions/$id'
    | '/fixtures/$id'
    | '/teams/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/backtesting'
    | '/_authenticated/competitions'
    | '/_authenticated/dashboard'
    | '/_authenticated/fixtures'
    | '/_authenticated/intelligence'
    | '/_authenticated/learning'
    | '/_authenticated/performance'
    | '/_authenticated/power-rankings'
    | '/_authenticated/predictions'
    | '/_authenticated/seasons'
    | '/_authenticated/settings'
    | '/_authenticated/standings'
    | '/_authenticated/system-status'
    | '/_authenticated/team-statistics'
    | '/_authenticated/teams'
    | '/_authenticated/competitions/$id'
    | '/_authenticated/fixtures/$id'
    | '/_authenticated/teams/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team-statistics': {
      id: '/_authenticated/team-statistics'
      path: '/team-statistics'
      fullPath: '/team-statistics'
      preLoaderRoute: typeof AuthenticatedTeamStatisticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system-status': {
      id: '/_authenticated/system-status'
      path: '/system-status'
      fullPath: '/system-status'
      preLoaderRoute: typeof AuthenticatedSystemStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/standings': {
      id: '/_authenticated/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof AuthenticatedStandingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seasons': {
      id: '/_authenticated/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof AuthenticatedSeasonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/predictions': {
      id: '/_authenticated/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof AuthenticatedPredictionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/power-rankings': {
      id: '/_authenticated/power-rankings'
      path: '/power-rankings'
      fullPath: '/power-rankings'
      preLoaderRoute: typeof AuthenticatedPowerRankingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning': {
      id: '/_authenticated/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof AuthenticatedLearningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intelligence': {
      id: '/_authenticated/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AuthenticatedIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fixtures': {
      id: '/_authenticated/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof AuthenticatedFixturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competitions': {
      id: '/_authenticated/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof AuthenticatedCompetitionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backtesting': {
      id: '/_authenticated/backtesting'
      path: '/backtesting'
      fullPath: '/backtesting'
      preLoaderRoute: typeof AuthenticatedBacktestingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams/$id': {
      id: '/_authenticated/teams/$id'
      path: '/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof AuthenticatedTeamsIdRouteImport
      parentRoute: typeof AuthenticatedTeamsRoute
    }
    '/_authenticated/fixtures/$id': {
      id: '/_authenticated/fixtures/$id'
      path: '/$id'
      fullPath: '/fixtures/$id'
      preLoaderRoute: typeof AuthenticatedFixturesIdRouteImport
      parentRoute: typeof AuthenticatedFixturesRoute
    }
    '/_authenticated/competitions/$id': {
      id: '/_authenticated/competitions/$id'
      path: '/$id'
      fullPath: '/competitions/$id'
      preLoaderRoute: typeof AuthenticatedCompetitionsIdRouteImport
      parentRoute: typeof AuthenticatedCompetitionsRoute
    }
  }
}

interface AuthenticatedCompetitionsRouteChildren {
  AuthenticatedCompetitionsIdRoute: typeof AuthenticatedCompetitionsIdRoute
}

const AuthenticatedCompetitionsRouteChildren: AuthenticatedCompetitionsRouteChildren =
  {
    AuthenticatedCompetitionsIdRoute: AuthenticatedCompetitionsIdRoute,
  }

const AuthenticatedCompetitionsRouteWithChildren =
  AuthenticatedCompetitionsRoute._addFileChildren(
    AuthenticatedCompetitionsRouteChildren,
  )

interface AuthenticatedFixturesRouteChildren {
  AuthenticatedFixturesIdRoute: typeof AuthenticatedFixturesIdRoute
}

const AuthenticatedFixturesRouteChildren: AuthenticatedFixturesRouteChildren = {
  AuthenticatedFixturesIdRoute: AuthenticatedFixturesIdRoute,
}

const AuthenticatedFixturesRouteWithChildren =
  AuthenticatedFixturesRoute._addFileChildren(
    AuthenticatedFixturesRouteChildren,
  )

interface AuthenticatedTeamsRouteChildren {
  AuthenticatedTeamsIdRoute: typeof AuthenticatedTeamsIdRoute
}

const AuthenticatedTeamsRouteChildren: AuthenticatedTeamsRouteChildren = {
  AuthenticatedTeamsIdRoute: AuthenticatedTeamsIdRoute,
}

const AuthenticatedTeamsRouteWithChildren =
  AuthenticatedTeamsRoute._addFileChildren(AuthenticatedTeamsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBacktestingRoute: typeof AuthenticatedBacktestingRoute
  AuthenticatedCompetitionsRoute: typeof AuthenticatedCompetitionsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFixturesRoute: typeof AuthenticatedFixturesRouteWithChildren
  AuthenticatedIntelligenceRoute: typeof AuthenticatedIntelligenceRoute
  AuthenticatedLearningRoute: typeof AuthenticatedLearningRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedPowerRankingsRoute: typeof AuthenticatedPowerRankingsRoute
  AuthenticatedPredictionsRoute: typeof AuthenticatedPredictionsRoute
  AuthenticatedSeasonsRoute: typeof AuthenticatedSeasonsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStandingsRoute: typeof AuthenticatedStandingsRoute
  AuthenticatedSystemStatusRoute: typeof AuthenticatedSystemStatusRoute
  AuthenticatedTeamStatisticsRoute: typeof AuthenticatedTeamStatisticsRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBacktestingRoute: AuthenticatedBacktestingRoute,
  AuthenticatedCompetitionsRoute: AuthenticatedCompetitionsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFixturesRoute: AuthenticatedFixturesRouteWithChildren,
  AuthenticatedIntelligenceRoute: AuthenticatedIntelligenceRoute,
  AuthenticatedLearningRoute: AuthenticatedLearningRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedPowerRankingsRoute: AuthenticatedPowerRankingsRoute,
  AuthenticatedPredictionsRoute: AuthenticatedPredictionsRoute,
  AuthenticatedSeasonsRoute: AuthenticatedSeasonsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStandingsRoute: AuthenticatedStandingsRoute,
  AuthenticatedSystemStatusRoute: AuthenticatedSystemStatusRoute,
  AuthenticatedTeamStatisticsRoute: AuthenticatedTeamStatisticsRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
